spring:
  datasource:
    url: jdbc:mysql://chrono-db.c49uc4ygev5k.us-east-1.rds.amazonaws.com:3306/chrono
    username: admin
    password: korea0228!
  jpa:
    properties:
      hibernate:
        format_sql:true
    show-sql: true
    hibernate:
      ddl-auto: update
chrono:
  point-per-hour: 1000