spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chrono
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql:true
    show-sql: true
    hibernate:
      ddl-auto: update
chrono:
  point-per-hour: 1000